//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumRot2.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public int id { get; set; }

        [Required(ErrorMessage = "El número de cédula es obligatorio.")]
        [StringLength(20, ErrorMessage = "El número de cédula no puede tener más de 20 caracteres.")]
        public string numero_cedula { get; set; }

        [Required(ErrorMessage = "El primer nombre es obligatorio.")]
        [StringLength(50, ErrorMessage = "El primer nombre no puede tener más de 50 caracteres.")]
        public string primer_nombre { get; set; }

        [StringLength(50, ErrorMessage = "El segundo nombre no puede tener más de 50 caracteres.")]
        public string segundo_nombre { get; set; }

        [Required(ErrorMessage = "El primer apellido es obligatorio.")]
        [StringLength(50, ErrorMessage = "El primer apellido no puede tener más de 50 caracteres.")]
        public string primer_apellido { get; set; }

        [StringLength(50, ErrorMessage = "El segundo apellido no puede tener más de 50 caracteres.")]
        public string segundo_apellido { get; set; }

        [Required(ErrorMessage = "El teléfono es obligatorio.")]
        [StringLength(15, ErrorMessage = "El teléfono no puede tener más de 15 caracteres.")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "El correo electrónico es obligatorio.")]
        [EmailAddress(ErrorMessage = "El correo electrónico no es válido.")]
        public string correo { get; set; }

        [StringLength(100, ErrorMessage = "La dirección no puede tener más de 100 caracteres.")]
        public string direccion { get; set; }

        public int edad { get; set; }

        [Required(ErrorMessage = "El género es obligatorio.")]
        public string genero { get; set; }
    }
}
